import 'package:food_application/modals/productModal.dart';

class Globals {
  static bool data = false;
  static List<Product> products = [
    Product(
      id: 1,
      name: "Pizza   \n-  Fast Food",
      price: 240,
      image: "assets/images/pizza.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 2,
      name: "Burger  \n-   Fast Food",
      price: 40,
      image: "assets/images/burger.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 3,
      name: "Momos   \n-  Fast Food",
      price: 50,
      image: "assets/images/momos.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 4,
      name: "Apple   \n-  Fruits",
      price: 40,
      image: "assets/images/apple.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 5,
      name: "Banana   \n-  Fruits",
      price: 30,
      image: "assets/images/banana.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 6,
      name: "Grapes   \n-  Fruits",
      price: 91,
      image: "assets/images/grapes.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 7,
      name: "Guava   \n-  Fruits",
      price: 67,
      image: "assets/images/guava.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 8,
      name: "Orange   \n-  Fruits",
      price: 45,
      image: "assets/images/orange.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 9,
      name: "Pineapple  \n-   Fruits",
      price: 50,
      image: "assets/images/pineapple.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 10,
      name: "Chocos   \n-  Grocery",
      price: 100,
      image: "assets/images/chocos.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 11,
      name: "Corn Flakes   \n-  Grocery",
      price: 120,
      image: "assets/images/corn_flakes.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 12,
      name: "Ice Cream   \n-  Grocery",
      price: 270,
      image: "assets/images/icecream.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 13,
      name: "Maggie   \n-  Grocery",
      price: 30,
      image: "assets/images/maggie.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 14,
      name: "Tomato   \n-  Veges",
      price: 40,
      image: "assets/images/tomato.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 15,
      name: "Sandwitch   \n-  Fast Food",
      price: 60,
      image: "assets/images/sandwitch.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 16,
      name: "Broccoli   \n-  Veges",
      price: 90,
      image: "assets/images/broccoli.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 17,
      name: "Capsicum   \n-  Veges",
      price: 70,
      image: "assets/images/capsicum.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 18,
      name: "Carrot   \n-  Veges",
      price: 50,
      image: "assets/images/carrot.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 19,
      name: "Lottie Chocopie   \n-  Grocery",
      price: 20,
      image: "assets/images/lottie.png",
      quantity: 0,
      like: "false",
    ),
    // Product(
    //   id: 20,
    //   name: "Salad - Veges",
    //   price: 580.0,
    //   image: "assets/images/salad.png",
    //   quantity: 0,
    //   like: "false",
    // ),
    // Product(
    //   id: 19,
    //   name: "Mix Salad - Veges",
    //   price: 580.0,
    //   image: "assets/images/salad2.png",
    //   quantity: 0,
    //   like: "false",
    // ),
  ];
}
